In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from hottbox.core import Tensor, TensorCPD, TensorTKD

[Return to Table of Contents](./0_Table_of_contents.ipynb)

# Efficient representation of multidimensional arrays

A tensor of order $N$ is said to be of **rank-1** if it can be represented as an outer product of $N$ vectors. 

The figure below illustrates an example of a rank-1 tensor $\mathbf{\underline{X}}$ and provides intuition on how to compute the operation of outer product:

<img src="./imgs/outerproduct.png" alt="Drawing" style="width: 500px;"/>


# Kruskal representation

For a third order tensor or rank $R$ the Kruskal representation can be expressed as follows:

$$
\mathbf{\underline{X}} = \sum_{r=1}^R \mathbf{\underline{X}}_r = \sum_{r=1}^R \lambda_{r} \cdot \mathbf{a}_r \circ \mathbf{b}_r \circ \mathbf{c}_r
$$

The vectors $\mathbf{a}_r, \mathbf{b}_r$ and $\mathbf{c}_r$ are oftentime combined into the corresponding **factor matrices**:

$$
\mathbf{A} = \Big[ \mathbf{a}_1 \cdots \mathbf{a}_R \Big] \quad
\mathbf{B} = \Big[ \mathbf{b}_1 \cdots \mathbf{b}_R \Big] \quad
\mathbf{C} = \Big[ \mathbf{c}_1 \cdots \mathbf{c}_R \Big] \quad
$$

Thus, if we employ the mode-$n$ product, the **Kruskal representation** takes the form:

$$
\mathbf{\underline{X}} = \mathbf{\underline{\Lambda}} \times_1 \mathbf{A} \times_2 \mathbf{B} \times_3 \mathbf{C} = \Big[\mathbf{\underline{\Lambda}}; \mathbf{A}, \mathbf{B}, \mathbf{C} \Big]
$$

where the elements on the super-diagonal of the core tensor $\mathbf{\underline{\Lambda}}$ are occupied by the values $\lambda_r$ and all other entries are equal to zero. This can be visualised as shown on figure below:

<img src="./imgs/TensorCPD.png" alt="Drawing" style="width: 500px;"/>


In [3]:
# Create factor matrices
I, J, K = 3, 4, 5
R = 2

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)

# Create core values
values = np.arange(R)
print('core values: {} \n'.format(values))

# Create Kruskal representation
tensor_cpd = TensorCPD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_cpd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_cpd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_cpd.core)
print(tensor_cpd.core.data)

tensor_full = tensor_cpd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
tensor_full.data

core values: [0 1] 

Kruskal representation of a tensor with rank=(2,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (3, 4, 5) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (3, 2)
Mode-1 factor matrix is of shape (4, 2)
Mode-2 factor matrix is of shape (5, 2)

	Core tensor
This tensor is of order 3 and consists of 8 elements.
Sizes and names of its modes are (2, 2, 2) and ['mode-0', 'mode-1', 'mode-2'] respectively.
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]]

Reconstructed Tensor: This tensor is of order 3 and consists of 60 elements.
Sizes and names of its modes are (3, 4, 5) and ['mode-0', 'mode-1', 'mode-2'] respectively.


array([[[  1.,   3.,   5.,   7.,   9.],
        [  3.,   9.,  15.,  21.,  27.],
        [  5.,  15.,  25.,  35.,  45.],
        [  7.,  21.,  35.,  49.,  63.]],

       [[  3.,   9.,  15.,  21.,  27.],
        [  9.,  27.,  45.,  63.,  81.],
        [ 15.,  45.,  75., 105., 135.],
        [ 21.,  63., 105., 147., 189.]],

       [[  5.,  15.,  25.,  35.,  45.],
        [ 15.,  45.,  75., 105., 135.],
        [ 25.,  75., 125., 175., 225.],
        [ 35., 105., 175., 245., 315.]]])

## **Assigment 1**

1. What is the order of a tensor if its Kruskal representation consists of 5 factor matrices.

2. What is the order of a tensor if its Kruskal representation consists of core tensor which has only 5 elements on the super-diagonal.

3. For a 3-rd order tensor that consists of 500 elements, provide three different Kruskal representations.

4. For a tensor that consits of 1000 elements, provide three Kruskal representations, each of which should have different number of factor matrices.

5. For a 4-th order tensor that consists of 2401 elements, provide Kruskal representation if its core tensor consisting of 81 elements.


### Solution: Part 1

In [4]:
answer_1_1 = "Order 5. Each order has a corresponding factor matrix."  # use this variable for your answer

print(answer_1_1)

Order 5. Each order has a corresponding factor matrix.


### Solution: Part 2

In [5]:
answer_1_2 = "This means that R=5. But does not give us any indication to the Tensor Order."  # use this variable for your answer

print(answer_1_2)

This means that R=5. But does not give us any indication to the Tensor Order.


### Solution: Part 3

In [6]:
#----------------------------First representation
# Create factor matrices
I, J, K = 5, 20, 5
R = 2

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)

# Create core values
values = np.arange(R)
print('core values: {} \n'.format(values))

# Create Kruskal representation
tensor_cpd = TensorCPD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_cpd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_cpd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_cpd.core)
print(tensor_cpd.core.data)

tensor_full = tensor_cpd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

core values: [0 1] 

Kruskal representation of a tensor with rank=(2,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (5, 20, 5) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (5, 2)
Mode-1 factor matrix is of shape (20, 2)
Mode-2 factor matrix is of shape (5, 2)

	Core tensor
This tensor is of order 3 and consists of 8 elements.
Sizes and names of its modes are (2, 2, 2) and ['mode-0', 'mode-1', 'mode-2'] respectively.
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 1.]]]

Reconstructed Tensor: This tensor is of order 3 and consists of 500 elements.
Sizes and names of its modes are (5, 20, 5) and ['mode-0', 'mode-1', 'mode-2'] respectively.


In [7]:
# ----------------------------Second representation
# Create factor matrices
I, J, K = 5, 20, 5
R = 3

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)

# Create core values
values = np.arange(R)
print('core values: {} \n'.format(values))

# Create Kruskal representation
tensor_cpd = TensorCPD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_cpd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_cpd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_cpd.core)
print(tensor_cpd.core.data)

tensor_full = tensor_cpd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

core values: [0 1 2] 

Kruskal representation of a tensor with rank=(3,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (5, 20, 5) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (5, 3)
Mode-1 factor matrix is of shape (20, 3)
Mode-2 factor matrix is of shape (5, 3)

	Core tensor
This tensor is of order 3 and consists of 27 elements.
Sizes and names of its modes are (3, 3, 3) and ['mode-0', 'mode-1', 'mode-2'] respectively.
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 2.]]]

Reconstructed Tensor: This tensor is of order 3 and consists of 500 elements.
Sizes and names of its modes are (5, 20, 5) and ['mode-0', 'mode-1', 'mode-2'] respectively.


In [8]:
# ----------------------------Third representation
# Create factor matrices
I, J, K = 5, 20, 5
R = 4

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)

# Create core values
values = np.arange(R)
print('core values: {} \n'.format(values))

# Create Kruskal representation
tensor_cpd = TensorCPD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_cpd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_cpd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_cpd.core)
print(tensor_cpd.core.data)

tensor_full = tensor_cpd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

core values: [0 1 2 3] 

Kruskal representation of a tensor with rank=(4,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (5, 20, 5) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (5, 4)
Mode-1 factor matrix is of shape (20, 4)
Mode-2 factor matrix is of shape (5, 4)

	Core tensor
This tensor is of order 3 and consists of 64 elements.
Sizes and names of its modes are (4, 4, 4) and ['mode-0', 'mode-1', 'mode-2'] respectively.
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 2. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 3.]]]

Reconstructed Tensor: This tensor is of order 3 and consists of 500 elements.
Sizes and names of its modes are (5, 20, 5) and ['mode-0', 'mode-1', 'mode-2'] respectively.


### Solution: Part 4

In [9]:
# ----------------------------First representation
# Create factor matrices
I, J, K = 1000, 1, 1
R = 4

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)

# Create core values
values = np.arange(R)
print('core values: {} \n'.format(values))

# Create Kruskal representation
tensor_cpd = TensorCPD(fmat=[A], core_values=values)

# Result preview
print(tensor_cpd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_cpd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_cpd.core)
print(tensor_cpd.core.data)

tensor_full = tensor_cpd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

core values: [0 1 2 3] 

Kruskal representation of a tensor with rank=(4,).
Factor matrices represent properties: ['mode-0']
With corresponding latent components described by (1000,) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (1000, 4)

	Core tensor
This tensor is of order 1 and consists of 4 elements.
Sizes and names of its modes are (4,) and ['mode-0'] respectively.
[0. 1. 2. 3.]

Reconstructed Tensor: This tensor is of order 1 and consists of 1000 elements.
Sizes and names of its modes are (1000,) and ['mode-0'] respectively.


In [10]:
# ----------------------------Second representation
# Create factor matrices
I, J, K = 100, 10, 1
R = 4

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)

# Create core values
values = np.arange(R)
print('core values: {} \n'.format(values))

# Create Kruskal representation
tensor_cpd = TensorCPD(fmat=[A, B], core_values=values)

# Result preview
print(tensor_cpd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_cpd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_cpd.core)
print(tensor_cpd.core.data)

tensor_full = tensor_cpd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

core values: [0 1 2 3] 

Kruskal representation of a tensor with rank=(4,).
Factor matrices represent properties: ['mode-0', 'mode-1']
With corresponding latent components described by (100, 10) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (100, 4)
Mode-1 factor matrix is of shape (10, 4)

	Core tensor
This tensor is of order 2 and consists of 16 elements.
Sizes and names of its modes are (4, 4) and ['mode-0', 'mode-1'] respectively.
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]]

Reconstructed Tensor: This tensor is of order 2 and consists of 1000 elements.
Sizes and names of its modes are (100, 10) and ['mode-0', 'mode-1'] respectively.


In [11]:
# ----------------------------Third representation
# Create factor matrices
I, J, K = 10, 20, 5
R = 4

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)

# Create core values
values = np.arange(R)
print('core values: {} \n'.format(values))

# Create Kruskal representation
tensor_cpd = TensorCPD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_cpd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_cpd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_cpd.core)
print(tensor_cpd.core.data)

tensor_full = tensor_cpd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

core values: [0 1 2 3] 

Kruskal representation of a tensor with rank=(4,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (10, 20, 5) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (10, 4)
Mode-1 factor matrix is of shape (20, 4)
Mode-2 factor matrix is of shape (5, 4)

	Core tensor
This tensor is of order 3 and consists of 64 elements.
Sizes and names of its modes are (4, 4, 4) and ['mode-0', 'mode-1', 'mode-2'] respectively.
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 2. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 3.]]]

Reconstructed Tensor: This tensor is of order 3 and consists of 1000 elements.
Sizes and names of its modes are (10, 20, 5) and ['mode-0', 'mode-1', 'mode-2'] respectively.


### Solution: Part 5

In [12]:
# Provide Kruskal representation here
# Create factor matrices
order = 4
R = int( np.power(81,1/order) )
I, J, K, L = 7, 7, 7, 7   # independent of R

A = np.arange(I * R).reshape(I, R)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * R).reshape(K, R)
D = np.arange(L * R).reshape(L, R)

# Create core values
values = np.arange(R)
print('core values: {} \n'.format(values))

# Create Kruskal representation
tensor_cpd = TensorCPD(fmat=[A, B, C, D], core_values=values)

# Result preview
print(tensor_cpd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_cpd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_cpd.core)
print(tensor_cpd.core.data)

tensor_full = tensor_cpd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

core values: [0 1 2] 

Kruskal representation of a tensor with rank=(3,).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2', 'mode-3']
With corresponding latent components described by (7, 7, 7, 7) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (7, 3)
Mode-1 factor matrix is of shape (7, 3)
Mode-2 factor matrix is of shape (7, 3)
Mode-3 factor matrix is of shape (7, 3)

	Core tensor
This tensor is of order 4 and consists of 81 elements.
Sizes and names of its modes are (3, 3, 3, 3) and ['mode-0', 'mode-1', 'mode-2', 'mode-3'] respectively.
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 1. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 2.]]]]

Reconst

# Tucker representation



<img src="./imgs/TensorTKD.png" alt="Drawing" style="width: 600px;"/>

For a tensor $\mathbf{\underline{X}} \in \mathbb{R}^{I \times J \times K}$ illustrated above, the **Tucker form** represents the tensor in hand through a dense core tensor $\mathbf{\underline{G}}$ with multi-linear rank ($Q, R, P$) and a set of accompanying factor matrices $\mathbf{A} \in \mathbb{R}^{I \times Q}, \mathbf{B} \in \mathbb{R}^{J \times R}$ and $\mathbf{C} \in \mathbb{R}^{K \times P}$.

$$
\mathbf{\underline{X}} = \sum_{q=1}^Q \sum_{r=1}^R \sum_{p=1}^P \mathbf{\underline{X}}_{qrp} = \sum_{q=1}^Q \sum_{r=1}^R \sum_{p=1}^P g_{qrp} \cdot \mathbf{a}_q \circ \mathbf{b}_r \circ \mathbf{c}_p
$$

The Tucker form of a tensor is closely related to the Kruskal representation and can be expressed through a 
sequence of mode-$n$ products in a similar way, that is

$$
\mathbf{\underline{X}} = \mathbf{\underline{G}} \times_1 \mathbf{A} \times_2 \mathbf{B} \times_3 \mathbf{C} = \Big[\mathbf{\underline{G}}; \mathbf{A}, \mathbf{B}, \mathbf{C} \Big]
$$


In [13]:
# Create factor matrices
I, J, K = 5, 6, 7  # define shape of the tensor in full form
Q, R, P = 2, 3, 4  # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)

# Create core values
values = np.arange(Q * R * P).reshape(Q, R, P)

# Create Tucker representation
tensor_tkd = TensorTKD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_tkd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_tkd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_tkd.core)
print(tensor_tkd.core.data)

tensor_full = tensor_tkd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

Tucker representation of a tensor with multi-linear rank=(2, 3, 4).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (5, 6, 7) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (5, 2)
Mode-1 factor matrix is of shape (6, 3)
Mode-2 factor matrix is of shape (7, 4)

	Core tensor
This tensor is of order 3 and consists of 24 elements.
Sizes and names of its modes are (2, 3, 4) and ['mode-0', 'mode-1', 'mode-2'] respectively.
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Reconstructed Tensor: This tensor is of order 3 and consists of 210 elements.
Sizes and names of its modes are (5, 6, 7) and ['mode-0', 'mode-1', 'mode-2'] respectively.


## **Assigment 2**

1. Core tensor of a Tucker representation consists of 1848 elements. Explain what tensor order should a tensor have to able to be represented in such form.

2. For a 4-th order tensor that consists of 1000 elements, provide three different Tucker representations.

3. For a 3-rd order tensor that consists of 500 elements, provide three different Tucker representations given that its core tensor consists of 42 elements.

4. Provide an intuition behind the main difference between the Tucker and Kruskal representations.


### Solution: Part 1

In [14]:
answer_2_1 = "There is no definitive answer here, we can go from order 1 to order 1848 and everything in between. We simply need to find the solutions to where the product of orders is equal to 1848, e.g. for a 3rd order we have multiple solutions where Q*R*P=1848 ."  # use this variable for your answer

print(answer_2_1)

There is no definitive answer here, we can go from order 1 to order 1848 and everything in between. We simply need to find the solutions to where the product of orders is equal to 1848, e.g. for a 3rd order we have multiple solutions where Q*R*P=1848 .


### Solution: Part 2

In [15]:
# ----------------------------First representation
# Create factor matrices
I, J, K, L = 5, 10, 5, 4   # define shape of the tensor in full form
Q, R, P, S = 2,  3, 4, 5   # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)
D = np.arange(L * S).reshape(L, S)

# Create core values
values = np.arange(Q * R * P * S).reshape(Q, R, P, S)

# Create Tucker representation
tensor_tkd = TensorTKD(fmat=[A, B, C, D], core_values=values)

# Result preview
print(tensor_tkd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_tkd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_tkd.core)
print(tensor_tkd.core.data)

tensor_full = tensor_tkd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

Tucker representation of a tensor with multi-linear rank=(2, 3, 4, 5).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2', 'mode-3']
With corresponding latent components described by (5, 10, 5, 4) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (5, 2)
Mode-1 factor matrix is of shape (10, 3)
Mode-2 factor matrix is of shape (5, 4)
Mode-3 factor matrix is of shape (4, 5)

	Core tensor
This tensor is of order 4 and consists of 120 elements.
Sizes and names of its modes are (2, 3, 4, 5) and ['mode-0', 'mode-1', 'mode-2', 'mode-3'] respectively.
[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]


In [16]:
# ----------------------------Second representation
# Create factor matrices
I, J, K, L = 5, 10, 5, 4   # define shape of the tensor in full form
Q, R, P, S = 1,  2, 3, 4   # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)
D= np.arange(L * S).reshape(L, S)

# Create core values
values = np.arange(Q * R * P * S).reshape(Q, R, P, S)

# Create Tucker representation
tensor_tkd = TensorTKD(fmat=[A, B, C, D], core_values=values)

# Result preview
print(tensor_tkd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_tkd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_tkd.core)
print(tensor_tkd.core.data)

tensor_full = tensor_tkd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

Tucker representation of a tensor with multi-linear rank=(1, 2, 3, 4).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2', 'mode-3']
With corresponding latent components described by (5, 10, 5, 4) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (5, 1)
Mode-1 factor matrix is of shape (10, 2)
Mode-2 factor matrix is of shape (5, 3)
Mode-3 factor matrix is of shape (4, 4)

	Core tensor
This tensor is of order 4 and consists of 24 elements.
Sizes and names of its modes are (1, 2, 3, 4) and ['mode-0', 'mode-1', 'mode-2', 'mode-3'] respectively.
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]

Reconstructed Tensor: This tensor is of order 4 and consists of 1000 elements.
Sizes and names of its modes are (5, 10, 5, 4) and ['mode-0', 'mode-1', 'mode-2', 'mode-3'] respectively.


In [17]:
# ----------------------------Third representation
# Create factor matrices
I, J, K, L = 5, 10, 5, 4   # define shape of the tensor in full form
Q, R, P, S = 5,  4, 3, 2   # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)
D= np.arange(L * S).reshape(L, S)

# Create core values
values = np.arange(Q * R * P * S).reshape(Q, R, P, S)

# Create Tucker representation
tensor_tkd = TensorTKD(fmat=[A, B, C, D], core_values=values)

# Result preview
print(tensor_tkd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_tkd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_tkd.core)
print(tensor_tkd.core.data)

tensor_full = tensor_tkd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

Tucker representation of a tensor with multi-linear rank=(5, 4, 3, 2).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2', 'mode-3']
With corresponding latent components described by (5, 10, 5, 4) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (5, 5)
Mode-1 factor matrix is of shape (10, 4)
Mode-2 factor matrix is of shape (5, 3)
Mode-3 factor matrix is of shape (4, 2)

	Core tensor
This tensor is of order 4 and consists of 120 elements.
Sizes and names of its modes are (5, 4, 3, 2) and ['mode-0', 'mode-1', 'mode-2', 'mode-3'] respectively.
[[[[  0   1]
   [  2   3]
   [  4   5]]

  [[  6   7]
   [  8   9]
   [ 10  11]]

  [[ 12  13]
   [ 14  15]
   [ 16  17]]

  [[ 18  19]
   [ 20  21]
   [ 22  23]]]


 [[[ 24  25]
   [ 26  27]
   [ 28  29]]

  [[ 30  31]
   [ 32  33]
   [ 34  35]]

  [[ 36  37]
   [ 38  39]
   [ 40  41]]

  [[ 42  43]
   [ 44  45]
   [ 46  47]]]


 [[[ 48  49]
   [ 50  51]
   [ 52  53]]

  [[ 54  55]
   [ 56  57]
   [ 58  5

### Solution: Part 3

In [18]:
# ----------------------------First representation
# Create factor matrices
I, J, K = 3, 3, 3  # define shape of the tensor in full form
Q, R, P = 2, 3, 7  # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)

# Create core values
values = np.arange(Q * R * P).reshape(Q, R, P)

# Create Tucker representation
tensor_tkd = TensorTKD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_tkd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_tkd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_tkd.core)
print(tensor_tkd.core.data)

tensor_full = tensor_tkd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

Tucker representation of a tensor with multi-linear rank=(2, 3, 7).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (3, 3, 3) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (3, 2)
Mode-1 factor matrix is of shape (3, 3)
Mode-2 factor matrix is of shape (3, 7)

	Core tensor
This tensor is of order 3 and consists of 42 elements.
Sizes and names of its modes are (2, 3, 7) and ['mode-0', 'mode-1', 'mode-2'] respectively.
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]]]

Reconstructed Tensor: This tensor is of order 3 and consists of 27 elements.
Sizes and names of its modes are (3, 3, 3) and ['mode-0', 'mode-1', 'mode-2'] respectively.


In [19]:
# ----------------------------Second representation
# Create factor matrices
I, J, K = 2, 6, 1  # define shape of the tensor in full form
Q, R, P = 2, 3, 7  # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)

# Create core values
values = np.arange(Q * R * P).reshape(Q, R, P)

# Create Tucker representation
tensor_tkd = TensorTKD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_tkd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_tkd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_tkd.core)
print(tensor_tkd.core.data)

tensor_full = tensor_tkd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

Tucker representation of a tensor with multi-linear rank=(2, 3, 7).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (2, 6, 1) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (2, 2)
Mode-1 factor matrix is of shape (6, 3)
Mode-2 factor matrix is of shape (1, 7)

	Core tensor
This tensor is of order 3 and consists of 42 elements.
Sizes and names of its modes are (2, 3, 7) and ['mode-0', 'mode-1', 'mode-2'] respectively.
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]]]

Reconstructed Tensor: This tensor is of order 3 and consists of 12 elements.
Sizes and names of its modes are (2, 6, 1) and ['mode-0', 'mode-1', 'mode-2'] respectively.


In [20]:
# ----------------------------Third representation
# Create factor matrices
I, J, K = 5, 6, 7  # define shape of the tensor in full form
Q, R, P = 2, 3, 7  # define multi-linear rank of the tensor in Tucker form

A = np.arange(I * Q).reshape(I, Q)
B = np.arange(J * R).reshape(J, R)
C = np.arange(K * P).reshape(K, P)

# Create core values
values = np.arange(Q * R * P).reshape(Q, R, P)

# Create Tucker representation
tensor_tkd = TensorTKD(fmat=[A, B, C], core_values=values)

# Result preview
print(tensor_tkd)

print('\n\tFactor matrices')
for mode, fmat in enumerate(tensor_tkd.fmat):
    print('Mode-{} factor matrix is of shape {}'.format(mode, fmat.shape))
    
print('\n\tCore tensor')
print(tensor_tkd.core)
print(tensor_tkd.core.data)

tensor_full = tensor_tkd.reconstruct()
print('\nReconstructed Tensor:',tensor_full)
# tensor_full.data

Tucker representation of a tensor with multi-linear rank=(2, 3, 7).
Factor matrices represent properties: ['mode-0', 'mode-1', 'mode-2']
With corresponding latent components described by (5, 6, 7) features respectively.

	Factor matrices
Mode-0 factor matrix is of shape (5, 2)
Mode-1 factor matrix is of shape (6, 3)
Mode-2 factor matrix is of shape (7, 7)

	Core tensor
This tensor is of order 3 and consists of 42 elements.
Sizes and names of its modes are (2, 3, 7) and ['mode-0', 'mode-1', 'mode-2'] respectively.
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]]]

Reconstructed Tensor: This tensor is of order 3 and consists of 210 elements.
Sizes and names of its modes are (5, 6, 7) and ['mode-0', 'mode-1', 'mode-2'] respectively.


### Solution: Part 4

In [21]:
answer_2_4 = "The Kruskal representation is foundationally a set of vectors, whereas the Tucker is a set of matrices. Although the Kruskal representation can be converted into a matrix, it is capable of sparsely defining an element of the tensor - from a set of vectors, which is not possible with the Tucker representation. This makes the Kruskal representation interesting from a compression standpoint, as sparsity is behind many compression algorithms."  # use this variable for your answer

print(answer_2_4)

The Kruskal representation is foundationally a set of vectors, whereas the Tucker is a set of matrices. Although the Kruskal representation can be converted into a matrix, it is capable of sparsely defining an element of the tensor - from a set of vectors, which is not possible with the Tucker representation. This makes the Kruskal representation interesting from a compression standpoint, as sparsity is behind many compression algorithms.
